
package com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Math", targetNamespace = "http://150.164.192.59:8080/Math", wsdlLocation = "http://150.164.192.59:8080/Math?wsdl")
public class Math
    extends Service
{

    private final static URL MATH_WSDL_LOCATION;
    private final static WebServiceException MATH_EXCEPTION;
    private final static QName MATH_QNAME = new QName("http://150.164.192.59:8080/Math", "Math");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://150.164.192.59:8080/Math?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATH_WSDL_LOCATION = url;
        MATH_EXCEPTION = e;
    }

    public Math() {
        super(__getWsdlLocation(), MATH_QNAME);
    }

    public Math(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATH_QNAME, features);
    }

    public Math(URL wsdlLocation) {
        super(wsdlLocation, MATH_QNAME);
    }

    public Math(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATH_QNAME, features);
    }

    public Math(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Math(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathPortType
     */
    @WebEndpoint(name = "MathPort")
    public MathPortType getMathPort() {
        return super.getPort(new QName("http://150.164.192.59:8080/Math", "MathPort"), MathPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathPortType
     */
    @WebEndpoint(name = "MathPort")
    public MathPortType getMathPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://150.164.192.59:8080/Math", "MathPort"), MathPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATH_EXCEPTION!= null) {
            throw MATH_EXCEPTION;
        }
        return MATH_WSDL_LOCATION;
    }

}
